# -*- coding: utf-8 -*-
"""Trabalho Final Amos.Regr. Lucas Malta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TWH8kGwcgZ-8vnd9HZ0KG3GerinExTaJ

# Análise de Regressão - Dataset Housing

O trabalho tem como objetivo a análise exploratória e modelagem de preços de imóveis utilizando regressão linear múltipla do dataset Housing.csv diponível em:https://www.kaggle.com/datasets/neurocipher/house-price-for-linear-regression/data.

O trabalho terá como guia responder as pergunta: Quais variaveis mais contribuem para valorização de preços em imóveis? Dados quantitativos são suficientes para explicar o preço de um imóvel? Adição de dados qualitativos elevam o poder explicativo do modelo?
"""

# Importação de bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from statsmodels.graphics.gofplots import qqplot
from statsmodels.graphics.tsaplots import plot_acf
from statsmodels.stats.diagnostic import het_breuschpagan
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from scipy import stats
import warnings
warnings.filterwarnings("ignore")

# Carregar dados
df = pd.read_csv('Housing.csv')

"""## 1. Análise Exploratória dos Dados

"""

# Visão geral dos dados
print(f"Dimensão: {df.shape[0]} observações, {df.shape[1]} variáveis")
print(f"\nValores nulos por variável:\n{df.isna().sum()}")
print(f"\nTipos de variáveis:\n{df.dtypes}")
df.head()

"""O conjunto de dados contém variáveis relacionadas às características de imóveis, sendo a variável resposta price (preço do imóvel, em unidades monetárias).

As variáveis independentes incluem dados numéricos, como area (área construída), bedrooms (número de quartos), bathrooms (banheiros), stories (número de andares) e parking (vagas de garagem), sendo todas do tipo variavel discreta, menos área construída que é contínua.

Além disso, há variáveis categóricas binárias (tipo objeto) que indicam a presença ou não de certos elementos: mainroad (acesso a rua principal), guestroom (sala de visitas), basement (porão), hotwaterheating (água quente), airconditioning (ar condicionado) e prefarea (localização em área de maior preferência).

A variável furnishingstatus (estado de mobília) é categórica ordinal, indicando níveis como "mobiliado", "semimobiliado" ou "não mobiliado". Todas as variáveis estão completas, sem valores nulos.
"""

# Estatísticas descritivas
df.describe()

# Matriz de correlação
numeric_cols = df.select_dtypes(include=[np.number]).columns
df_numeric = df[numeric_cols]

plt.figure(figsize=(12, 8))
sns.heatmap(df_numeric.corr(), annot=True, cmap="RdYlGn", fmt=".2f", linewidths=0.5)
plt.title('Matriz de Correlação de Pearson')
plt.tight_layout()
plt.show()

"""## 2. Análise de Outliers e Normalização

"""

# Normalização Z-Score
scaler = StandardScaler()
df_normalized = pd.DataFrame(
    scaler.fit_transform(df_numeric),
    columns=df_numeric.columns
)

# Boxplots normalizados
fig, ax = plt.subplots(figsize=(12, 6))
bp = ax.boxplot([df_normalized[col].values for col in numeric_cols],
                labels=numeric_cols, patch_artist=True)

colors = plt.cm.Set2(np.linspace(0, 1, len(numeric_cols)))
for patch, color in zip(bp['boxes'], colors):
    patch.set_facecolor(color)
    patch.set_alpha(0.7)

ax.set_title('Boxplots - Valores Normalizados (Z-Score)')
ax.set_ylabel('Z-Score')
ax.axhline(y=0, color='red', linestyle='--', alpha=0.5, label='Média = 0')
ax.tick_params(axis='x', rotation=45)
ax.grid(True, alpha=0.3, axis='y')
ax.legend()
plt.tight_layout()
plt.show()

# Tabela comparativa: original vs normalizado
comparison_stats = []
for col in numeric_cols:
    stats_orig = df[col].describe()
    stats_norm = df_normalized[col].describe()
    comparison_stats.append({
        'Variável': col,
        'Média_Orig': f"{stats_orig['mean']:,.2f}",
        'Média_Norm': f"{stats_norm['mean']:.3f}",
        'Mediana_Orig': f"{stats_orig['50%']:,.2f}",
        'Mediana_Norm': f"{stats_norm['50%']:.3f}",
        'Std_Orig': f"{stats_orig['std']:,.2f}",
        'Std_Norm': f"{stats_norm['std']:.3f}"
    })

pd.set_option('display.max_columns', None)
print(pd.DataFrame(comparison_stats).to_string(index=False))

# Análise gráfica de pares
sns.pairplot(df_numeric, corner=True)
plt.suptitle("Análise Gráfica de Pares", y=1.02)
plt.show()

"""## 3. Transformação Logarítmica do Preço

"""

# Transformação logarítmica
df['log_price'] = np.log(df['price'])

# Visualização da transformação
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

axes[0].hist(df['price'], bins=30, edgecolor='black', alpha=0.7, color='lightblue')
axes[0].set_xlabel('Preço Original ($)')
axes[0].set_ylabel('Frequência')
axes[0].set_title('Distribuição do Preço Original')
axes[0].axvline(df['price'].mean(), color='red', linestyle='--', label=f'Média: ${df["price"].mean():,.0f}')
axes[0].legend()

axes[1].hist(df['log_price'], bins=30, edgecolor='black', alpha=0.7, color='lightgreen')
axes[1].set_xlabel('log(Preço)')
axes[1].set_ylabel('Frequência')
axes[1].set_title('Distribuição do log(Preço)')
axes[1].axvline(df['log_price'].mean(), color='red', linestyle='--', label=f'Média: {df["log_price"].mean():.2f}')
axes[1].legend()

plt.suptitle('Transformação Logarítmica do Preço', fontweight='bold')
plt.tight_layout()
plt.show()

# Comparação de assimetria
print(f"Assimetria do preço original: {df['price'].skew():.4f}")
print(f"Assimetria do log(preço): {df['log_price'].skew():.4f}")

"""## 4. Modelos de Regressão Linear

"""

# Modelo 1: Apenas variáveis numéricas
print("Modelo 1: Apenas variáveis numéricas")
print("-" * 60)

df_num = df.select_dtypes(include=[np.number])
X_numeric = df_num.drop(['price', 'log_price'], axis=1)
y_numeric = df_num['log_price']

X_numeric_const = sm.add_constant(X_numeric)
modelo_numeric = sm.OLS(y_numeric, X_numeric_const).fit()

print(f"Variáveis: {list(X_numeric.columns)}")
print(f"Observações: {X_numeric.shape[0]}")
print(modelo_numeric.summary())

# Modelo 2: Com variáveis categóricas
print("Modelo 2: Com variáveis categóricas")
print("-" * 60)

categorical_cols = df.select_dtypes(include=['object']).columns
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)
df_encoded = df_encoded.astype(float)

X_full = df_encoded.drop(['price', 'log_price'], axis=1)
y_full = df_encoded['log_price']

X_full_const = sm.add_constant(X_full)
modelo_full = sm.OLS(y_full, X_full_const).fit()

print(f"Total de variáveis após encoding: {X_full.shape[1]}")
print(modelo_full.summary())

# Comparação dos modelos
print("Comparação dos modelos")
print("-" * 60)

# Calcular MAE e MSE para o modelo numérico (na escala original)
y_numeric_original = np.exp(y_numeric)
y_pred_numeric_original = np.exp(modelo_numeric.fittedvalues)
mae_numeric = mean_absolute_error(y_numeric_original, y_pred_numeric_original)
mse_numeric = mean_squared_error(y_numeric_original, y_pred_numeric_original)

# Calcular MAE e MSE para o modelo completo (na escala original)
y_full_original = np.exp(y_full)
y_pred_full_original = np.exp(modelo_full.fittedvalues)
mae_full = mean_absolute_error(y_full_original, y_pred_full_original)
mse_full = mean_squared_error(y_full_original, y_pred_full_original)


comparacao = pd.DataFrame({
    'Métrica': ['R²', 'R² Ajustado', 'Variáveis', 'AIC', 'BIC', 'MAE', 'MSE'],
    'Modelo Numérico': [
        f"{modelo_numeric.rsquared:.4f}",
        f"{modelo_numeric.rsquared_adj:.4f}",
        f"{len(modelo_numeric.params)}",
        f"{modelo_numeric.aic:.1f}",
        f"{modelo_numeric.bic:.1f}",
        f"{mae_numeric:,.0f}",
        f"{mse_numeric:,.0f}"
    ],
    'Modelo Completo': [
        f"{modelo_full.rsquared:.4f}",
        f"{modelo_full.rsquared_adj:.4f}",
        f"{len(modelo_full.params)}",
        f"{modelo_full.aic:.1f}",
        f"{modelo_full.bic:.1f}",
        f"{mae_full:,.0f}",
        f"{mse_full:,.0f}"
    ]
})
print(comparacao.to_string(index=False))

# Função para extrair variáveis significativas
def get_significant_vars(modelo, nome):
    coef_df = pd.DataFrame({
        'Variável': modelo.params.index,
        'Coeficiente': modelo.params.values,
        'P-valor': modelo.pvalues.values
    })
    signif = coef_df[(coef_df['P-valor'] < 0.05) & (coef_df['Variável'] != 'const')]
    signif = signif.sort_values('Coeficiente', key=abs, ascending=False)

    print(f"\n{nome} - {len(signif)} variáveis significativas (top 5):")
    for _, row in signif.head(5).iterrows():
        perc_effect = (np.exp(row['Coeficiente']) - 1) * 100
        print(f"  {row['Variável']}: coef={row['Coeficiente']:.4f}, p={row['P-valor']:.4f}, efeito={perc_effect:+.1f}%")
    return signif

signif_numeric = get_significant_vars(modelo_numeric, "Modelo Numérico")
signif_full = get_significant_vars(modelo_full, "Modelo Completo")

"""## 5. Análise de Resíduos

"""

# Análise gráfica de resíduos - Modelo Numérico
residuos_numeric = modelo_numeric.resid

fig, axes = plt.subplots(2, 2, figsize=(14, 10))

residuos_numeric.plot(title="Resíduos", ax=axes[0, 0])
axes[0, 0].axhline(y=0, color='r', linestyle='--')

sns.histplot(residuos_numeric, kde=True, ax=axes[0, 1])
axes[0, 1].set_title("Distribuição dos Resíduos")

plot_acf(residuos_numeric, lags=40, ax=axes[1, 0])

qqplot(residuos_numeric, line='s', ax=axes[1, 1])

plt.suptitle('Análise de Resíduos - Modelo Numérico', fontweight='bold')
plt.tight_layout()
plt.show()

# Análise gráfica de resíduos - Modelo Completo
residuos_full = modelo_full.resid

fig, axes = plt.subplots(2, 2, figsize=(14, 10))

residuos_full.plot(title="Resíduos", ax=axes[0, 0])
axes[0, 0].axhline(y=0, color='r', linestyle='--')

sns.histplot(residuos_full, kde=True, ax=axes[0, 1])
axes[0, 1].set_title("Distribuição dos Resíduos")

plot_acf(residuos_full, lags=40, ax=axes[1, 0])

qqplot(residuos_full, line='s', ax=axes[1, 1])

plt.suptitle('Análise de Resíduos - Modelo Completo', fontweight='bold')
plt.tight_layout()
plt.show()

"""## 6. Testes de Hipótese

"""

# Teste de normalidade (Shapiro-Wilk)
print("Teste de normalidade dos resíduos (Shapiro-Wilk)")
print("-" * 60)

stat_num, p_num = stats.shapiro(modelo_numeric.resid)
print(f"Modelo Numérico: estatística={stat_num:.6f}, p-valor={p_num:.6f}")
print(f"  Conclusão: {'Resíduos normais (não rejeita H0)' if p_num > 0.05 else 'Resíduos não normais (rejeita H0)'}")

stat_full, p_full = stats.shapiro(modelo_full.resid)
print(f"\nModelo Completo: estatística={stat_full:.6f}, p-valor={p_full:.6f}")
print(f"  Conclusão: {'Resíduos normais (não rejeita H0)' if p_full > 0.05 else 'Resíduos não normais (rejeita H0)'}")

# Teste de homocedasticidade (Breusch-Pagan)
print("Teste de homocedasticidade (Breusch-Pagan)")
print("-" * 60)

lm_num, p_lm_num, f_num, pf_num = het_breuschpagan(modelo_numeric.resid, modelo_numeric.model.exog)
print(f"Modelo Numérico: LM={lm_num:.4f}, p-valor={p_lm_num:.6f}")
print(f"  Conclusão: {'Homocedástico (não rejeita H0)' if p_lm_num > 0.05 else 'Heterocedástico (rejeita H0)'}")

lm_full, p_lm_full, f_full, pf_full = het_breuschpagan(modelo_full.resid, modelo_full.model.exog)
print(f"\nModelo Completo: LM={lm_full:.4f}, p-valor={p_lm_full:.6f}")
print(f"  Conclusão: {'Homocedástico (não rejeita H0)' if p_lm_full > 0.05 else 'Heterocedástico (rejeita H0)'}")

# Gráficos de homocedasticidade
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

sns.scatterplot(x=modelo_numeric.fittedvalues, y=residuos_numeric, ax=axes[0])
axes[0].axhline(y=0, color='red', linestyle='--')
axes[0].set_title('Homocedasticidade - Modelo Numérico')
axes[0].set_xlabel('Valores Ajustados')
axes[0].set_ylabel('Resíduos')
axes[0].grid(True, alpha=0.3)

sns.scatterplot(x=modelo_full.fittedvalues, y=residuos_full, ax=axes[1])
axes[1].axhline(y=0, color='red', linestyle='--')
axes[1].set_title('Homocedasticidade - Modelo Completo')
axes[1].set_xlabel('Valores Ajustados')
axes[1].set_ylabel('Resíduos')
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# Resíduos padronizados
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

resid_pad_num = modelo_numeric.get_influence().resid_studentized_internal
axes[0].scatter(y_numeric, resid_pad_num)
axes[0].axhline(y=3, color='r', linestyle='--')
axes[0].axhline(y=-3, color='r', linestyle='--')
axes[0].set_title('Resíduos Padronizados - Modelo Numérico')
axes[0].set_xlabel('log(Preço)')
axes[0].set_ylabel('Resíduos Padronizados')
axes[0].grid(True, alpha=0.3)

resid_pad_full = modelo_full.get_influence().resid_studentized_internal
axes[1].scatter(y_full, resid_pad_full)
axes[1].axhline(y=3, color='r', linestyle='--')
axes[1].axhline(y=-3, color='r', linestyle='--')
axes[1].set_title('Resíduos Padronizados - Modelo Completo')
axes[1].set_xlabel('log(Preço)')
axes[1].set_ylabel('Resíduos Padronizados')
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

print("="*80)
print("ANÁLISE DE MULTICOLINEARIDADE - VIF")
print("="*80)

# Modelo Numérico
vif_numeric = pd.DataFrame()
vif_numeric['Variável'] = X_numeric.columns
vif_numeric['VIF'] = [variance_inflation_factor(X_numeric.values, i)
                      for i in range(X_numeric.shape[1])]
vif_numeric = vif_numeric.sort_values('VIF', ascending=False)

print("\nMODELO NUMÉRICO - VIF:")
print(vif_numeric.to_string(index=False))

# Modelo Completo
vif_full = pd.DataFrame()
vif_full['Variável'] = X_full.columns
vif_full['VIF'] = [variance_inflation_factor(X_full.values, i)
                   for i in range(X_full.shape[1])]
vif_full = vif_full.sort_values('VIF', ascending=False)

print("\nMODELO COMPLETO - VIF (top 10):")
print(vif_full.head(10).to_string(index=False))

print("\n" + "="*80)
print("INTERPRETAÇÃO DO VIF:")
print("VIF < 5: Multicolinearidade baixa")
print("5 ≤ VIF < 10: Multicolinearidade moderada")
print("VIF ≥ 10: Multicolinearidade alta (problemática)")

# Contar variáveis problemáticas
alto_vif_numeric = vif_numeric[vif_numeric['VIF'] >= 5]
alto_vif_full = vif_full[vif_full['VIF'] >= 10]

print(f"\nModelo Numérico:")
print(f"- Variáveis com VIF ≥ 5: {len(alto_vif_numeric)}/{len(vif_numeric)}")
print(f"- Variáveis com VIF ≥ 10: {len(vif_numeric[vif_numeric['VIF'] >= 10])}/{len(vif_numeric)}")

print(f"\nModelo Completo:")
print(f"- Variáveis com VIF ≥ 10: {len(alto_vif_full)}/{len(vif_full)}")

# Verificar variáveis específicas com alto VIF
if len(alto_vif_full) > 0:
    print(f"\nVariáveis com VIF ≥ 10 no modelo completo:")
    for _, row in alto_vif_full.head(5).iterrows():
        print(f"  {row['Variável']}: VIF = {row['VIF']:.2f}")

"""## 7. Validação do Modelo

"""

# Validação com treino/teste
X_train, X_test, y_train, y_test = train_test_split(X_full, y_full, test_size=0.3, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)
y_pred_log = model.predict(X_test)

# Converter para escala original
y_pred_original = np.exp(y_pred_log)
y_test_original = np.exp(y_test)

# Métricas
rmse = np.sqrt(mean_squared_error(y_test_original, y_pred_original))
r2 = r2_score(y_test_original, y_pred_original)
mae = mean_absolute_error(y_test_original, y_pred_original) # Adicionado MAE
mse = mean_squared_error(y_test_original, y_pred_original) # Adicionado MSE
mape = np.mean(np.abs((y_test_original - y_pred_original) / y_test_original)) * 100

print("Validação do modelo (conjunto de teste)")
print("-" * 60)
print(f"RMSE: ${rmse:,.0f}")
print(f"R²: {r2:.4f}")
print(f"MAE: ${mae:,.0f}") # Exibindo MAE
print(f"MSE: ${mse:,.0f}") # Exibindo MSE
print(f"MAPE: {mape:.1f}%")

"""## 8. Conclusão

"""

# Resumo dos resultados
print("Resumo da análise")
print("-" * 60)
print(f"Diferença no R²: {modelo_full.rsquared - modelo_numeric.rsquared:.4f}")
print(f"Diferença no R² Ajustado: {modelo_full.rsquared_adj - modelo_numeric.rsquared_adj:.4f}")
print(f"Variáveis adicionais: {len(modelo_full.params) - len(modelo_numeric.params)}")

melhor_aic = "Completo" if modelo_full.aic < modelo_numeric.aic else "Numérico"
print(f"Melhor modelo pelo AIC: {melhor_aic}")

print("\nDiagnóstico dos resíduos (Modelo Completo):")
print(f"  Normalidade (Shapiro-Wilk): p={p_full:.4f} - {'Aceita H0' if p_full > 0.05 else 'Rejeita H0'}")
print(f"  Homocedasticidade (Breusch-Pagan): p={p_lm_full:.4f} - {'Aceita H0' if p_lm_full > 0.05 else 'Rejeita H0'}")

print("\nMulticolinearidade (VIF):")
if len(alto_vif_full) > 0:
    print(f"  Modelo Numérico: {len(alto_vif_numeric)} variáveis com VIF \u2265 5 (e {len(vif_numeric[vif_numeric['VIF'] >= 10])} com VIF \u2265 10).")
    print(f"  Modelo Completo: {len(alto_vif_full)} variáveis com VIF \u2265 10 (e {len(vif_full[vif_full['VIF'] >= 5])} com VIF \u2265 5).")
else:
    print("  Não foram identificadas variáveis com multicolinearidade alta (VIF \u2265 10) no Modelo Completo.")

"""A análise mostrou que o preço dos imóveis é melhor explicado quando combinamos variáveis numéricas e categóricas: o modelo completo elevou o R² para cerca de 0,70 (vs. 0,54 no modelo apenas numérico) e reduziu MAE/MSE após a transformação logarítmica do preço.

As variáveis mais influentes incluem área, banheiros, andares, vagas e, entre as qualitativas, presença de ar-condicionado, aquecimento, localização preferencial e acesso à via principal, indicando que atributos de conforto e localização agregam valor significativo. Contudo, ambos os modelos exibem heterocedasticidade, sugerindo cautela na leitura de erros-padrão. Observou-se também multicolinearidade elevada em bedrooms (VIF > 10), o que pode distorcer coeficientes.

No conjunto de teste, o modelo completo manteve desempenho consistente, com R² em torno de 0,66 e MAPE próximo de 20%, indicando boa capacidade de generalização. A união ou retirada de variáveis com alta multicolinearidade pode auxiliar a dar maior sustentação ao modelo.

"""